# Wealth Scenerio Simulator
The goal of this is to get the different scenarios of capital allocations (holding in bank, holdng crypto, holding stocks) in regards to different scenerios such as:
- Paying the house off and saving money to live off of
- Paying the house off then investing (With different ratios)
- Paying good chunk of interest off on house and start investing
- Start investing right away pay regular payments on house

In [33]:
pip install numpy-financial

Collecting numpy-financial
  Downloading numpy_financial-1.0.0-py3-none-any.whl (14 kB)
Requirement already satisfied: numpy>=1.15 in c:\users\btindol\anaconda3\lib\site-packages (from numpy-financial) (1.20.1+mkl)
Installing collected packages: numpy-financial
Successfully installed numpy-financial-1.0.0
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.0.1; however, version 21.1.1 is available.
You should consider upgrading via the 'C:\Users\btindol\Anaconda3\python.exe -m pip install --upgrade pip' command.

In [34]:
import pandas as pd
import numpy as np
from datetime import date
import numpy_financial as npf

In [9]:
start_date = date.today() # starting today which happens to be the first 

years = 30 # 30 years

payments_year = 12 # 12 payments a year..so 12 periods

# Gives you a start date that increases monthly for the next 30 years... 
rng = pd.date_range(start_date, periods=years * payments_year, freq='MS')
rng

DatetimeIndex(['2021-05-01', '2021-06-01', '2021-07-01', '2021-08-01',
               '2021-09-01', '2021-10-01', '2021-11-01', '2021-12-01',
               '2022-01-01', '2022-02-01',
               ...
               '2050-07-01', '2050-08-01', '2050-09-01', '2050-10-01',
               '2050-11-01', '2050-12-01', '2051-01-01', '2051-02-01',
               '2051-03-01', '2051-04-01'],
              dtype='datetime64[ns]', length=360, freq='MS')

In [60]:
# Makes a date range from today to number of years yous specify chunking into months..
######################################################################################
######################################################################################
# Parameter making
# year parameters
start_date = date.today() # starting today which happens to be the first 
Years = 30 # 30 years
payment_periods_in_year = 12 # 12 payments a year..so 12 periods
rng = pd.date_range(start_date, periods=years * payment_periods_in_year, freq='MS')

Total_Mortgage_Cost_At_Start = 142000
Interest_Rate = 0.02875
Payment_Periods_In_Year = 12 #
Additional_Mortgage_Principal_Added = 50

MonthlyIncome = 6000
Expenses = 3000
StockAnnualReturn
StockAnnualReturnMonthly = (StockAnnualReturn/12)/100 # annual return divided by 12 is .88 and .88 is really .0088 so divide by 100


#####################################################################################
######################################################################################
# Index creation
df = pd.DataFrame(index=rng,columns=['Monthly_Income','Expenses','Bank_Balance_Post_Expenses','Bank_Account_Balance', 'Mortgage_Total_Payment', 'Mortgage_Principal_Payment','Mortgage_Interest_Payment','Additional_Mortgage_Principal_Added','Cumulative_Mortgage_Principal_Paid','Cumulative_Mortgage_Interest_Paid','Current_Mortgage_Balance_Left_To_Pay','Dividend_Stock_Balance','Monthly_Dividends','Crypto_Balance'], dtype='float')
df.reset_index(inplace=True)
df.index += 1
df.index.name = "Period"
######################################################################################
######################################################################################

df["Monthly_Income"] =MonthlyIncome
df["Expenses"] = Expenses
df["Bank_Balance_Post_Expenses"] = df["Monthly_Income"] -df["Expenses"]
df["Bank_Account_Balance"] = df["Bank_Balance_Post_Expenses"].cumsum()

df["Mortgage_Total_Payment"] = round(npf.pmt(Interest_Rate/Payment_Periods_In_Year, Years*Payment_Periods_In_Year, Total_Mortgage_Cost_At_Start),2)
df["Mortgage_Principal_Payment"] = npf.ppmt(Interest_Rate/Payment_Periods_In_Year, df.index, Years*Payment_Periods_In_Year, Total_Mortgage_Cost_At_Start)
df["Mortgage_Interest_Payment"] = npf.ipmt(Interest_Rate/Payment_Periods_In_Year, df.index, Years*Payment_Periods_In_Year, Total_Mortgage_Cost_At_Start)
df["Additional_Mortgage_Principal_Added"] = -Additional_Mortgage_Principal_Added

#Store the Cumulative Principal Payments and ensure it never gets larger than the original principal
df["Cumulative_Mortgage_Principal_Paid"] = (df["Mortgage_Principal_Payment"] + df["Additional_Mortgage_Principal_Added"]).cumsum()
df["Cumulative_Mortgage_Principal_Paid"] = round(df["Cumulative_Mortgage_Principal_Paid"].clip(lower=-Total_Mortgage_Cost_At_Start),2)
df["Cumulative_Mortgage_Interest_Paid"] = round(df["Mortgage_Interest_Payment"].cumsum(),2)
df["Current_Mortgage_Balance_Left_To_Pay"] = Total_Mortgage_Cost_At_Start + df["Cumulative_Mortgage_Principal_Paid"]
df

,index,Monthly_Income,Expenses,Bank_Balance_Post_Expenses,Bank_Account_Balance,Mortgage_Total_Payment,Mortgage_Principal_Payment,Mortgage_Interest_Payment,Additional_Mortgage_Principal_Added,Cumulative_Mortgage_Principal_Paid,Cumulative_Mortgage_Interest_Paid,Current_Mortgage_Balance_Left_To_Pay,Dividend_Stock_Balance,Monthly_Dividends,Crypto_Balance
Period,,,,,,,,,,,,,,,
1,2021-05-01,6000,3000,3000,3000,-589.15,-248.938984,-340.208333,-50,-298.94,-340.21,141701.06,NaN,NaN,NaN
2,2021-06-01,6000,3000,3000,6000,-589.15,-249.535400,-339.611917,-50,-598.47,-679.82,141401.53,NaN,NaN,NaN
3,2021-07-01,6000,3000,3000,9000,-589.15,-250.133246,-339.014072,-50,-898.61,-1018.83,141101.39,NaN,NaN,NaN
4,2021-08-01,6000,3000,3000,12000,-589.15,-250.732523,-338.414794,-50,-1199.34,-1357.25,140800.66,NaN,NaN,NaN
5,2021-09-01,6000,3000,3000,15000,-589.15,-251.333237,-337.814081,-50,-1500.67,-1695.06,140499.33,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356,2050-12-01,6000,3000,3000,1068000,-589.15,-582.140267,-7.007050,-50,-142000.00,-70078.99,0.00,NaN,NaN,NaN
357,2051-01-01,6000,3000,3000,1071000,-589.15,-583.534978,-5.612339,-50,-142000.00,-70084.60,0.00,NaN,NaN,NaN
358,2051-02-01,6000,3000,3000,1074000,-589.15,-584.933031,-4.214287,-50,-142000.00,-70088.81,0.00,NaN,NaN,NaN
359,2051-03-01,6000,3000,3000,1077000,-589.15,-586.334433,-2.812885,-50,-142000.00,-70091.63,0.00,NaN,NaN,NaN
360,2051-04-01,6000,3000,3000,1080000,-589.15,-587.739192,-1.408125,-50,-142000.00,-70093.03,0.00,NaN,NaN,NaN

In [64]:
StockAnnualReturnMonthly = (10/12)/100 # 10% divided by number of months
StockAnnualReturnMonthly

0.008333333333333333

In [63]:
100 * .8333
100

83.33

In [66]:
0.008333333333333333 * 12

0.1